"""replace parent_claim_id with parent_claim_ids json

Revision ID: 23fbf1ca0df3
Revises: c2d9e1f4a8b6
Create Date: 2026-05-18 12:04:13.601489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fbf1ca0df3'
down_revision: Union[str, Sequence[str], None] = 'c2d9e1f4a8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('parent_claim_ids', sa.JSON(), server_default='[]', nullable=False))
    op.drop_constraint('claim_parent_claim_id_fkey', 'claim', type_='foreignkey')
    op.drop_column('claim', 'parent_claim_id')
    op.drop_index('ix_invention_disclosure_document_idf_id', table_name='invention_disclosure_document')
    op.drop_index('ix_inventor_qa_document_qna_id', table_name='inventor_qa_document')
    op.drop_index('ix_research_report_document_research_report_id', table_name='research_report_document')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_research_report_document_research_report_id', 'research_report_document', ['research_report_id'], unique=False)
    op.create_index('ix_inventor_qa_document_qna_id', 'inventor_qa_document', ['qna_id'], unique=False)
    op.create_index('ix_invention_disclosure_document_idf_id', 'invention_disclosure_document', ['idf_id'], unique=False)
    op.add_column('claim', sa.Column('parent_claim_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('claim_parent_claim_id_fkey', 'claim', 'claim', ['parent_claim_id'], ['claim_id'])
    op.drop_column('claim', 'parent_claim_ids')
    # ### end Alembic commands ###
