"""initial schema

Revision ID: a953e5ca1012
Revises: 
Create Date: 2026-04-10 14:26:49.558352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a953e5ca1012'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent',
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('patent_name', sa.String(length=255), nullable=False),
    sa.Column('patent_owner', sa.String(length=255), nullable=False),
    sa.Column('patent_draft', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patent_id')
    )
    op.create_table('claim',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.Integer(), nullable=False),
    sa.Column('claim_dependency_type', sa.String(length=20), nullable=False),
    sa.Column('claim_category', sa.String(length=20), nullable=False),
    sa.Column('parent_claim_id', sa.Integer(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_claim_id'], ['claim.claim_id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.patent_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('element',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('element_name', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.Integer(), nullable=True),
    sa.Column('definition_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.patent_id'], ),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_table('invention_disclosure',
    sa.Column('idf_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('prior_art_and_problems', sa.Text(), nullable=True),
    sa.Column('closest_prior_patents', sa.Text(), nullable=True),
    sa.Column('novel_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.patent_id'], ),
    sa.PrimaryKeyConstraint('idf_id'),
    sa.UniqueConstraint('patent_id')
    )
    op.create_table('inventor_qa',
    sa.Column('qna_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('questions_and_answers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.patent_id'], ),
    sa.PrimaryKeyConstraint('qna_id'),
    sa.UniqueConstraint('patent_id')
    )
    op.create_table('research_report',
    sa.Column('research_report_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('search_strategy', sa.Text(), nullable=True),
    sa.Column('classification_and_keywords', sa.Text(), nullable=True),
    sa.Column('element_patent_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.patent_id'], ),
    sa.PrimaryKeyConstraint('research_report_id'),
    sa.UniqueConstraint('patent_id')
    )
    op.create_table('claim_element',
    sa.Column('claim_element_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.claim_id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['element.element_id'], ),
    sa.PrimaryKeyConstraint('claim_element_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_element')
    op.drop_table('research_report')
    op.drop_table('inventor_qa')
    op.drop_table('invention_disclosure')
    op.drop_table('element')
    op.drop_table('claim')
    op.drop_table('patent')
    # ### end Alembic commands ###
